runtime: python39

instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 2
  target_cpu_utilization: 0.65

env_variables:
  FLASK_ENV: "production"

handlers:
  - url: /static
    static_dir: static
    
  - url: /.*
    script: auto